<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MCG_AutoPlay.Tests</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Core\**\*.cs" Link="Core\%(Filename)%(Extension)" />
    <Compile Include="..\..\Game\**\*.cs" Link="Game\%(Filename)%(Extension)" />
    <Compile Include="Program.cs" />
    <Compile Include="Stubs\**\*.cs" Link="Stubs\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
